### ISSUE TITLE
Basic PostgresSQL support and support for data model

### ISSUE THREAD

**Issue by klown** [fluid-project/personal-data-server#2]
The Preferences Service persistence layer will be handled by a PostgreSQL database. The database is where user preferences are ultimately stored.  A set of common operations and utilities include:

- A way to start and stop a postgres server,
- An infusion component to access the database and handle requests to add, retrieve, and modify records.

In addition, the specific data models documented in "[Data Model](https://github.com/fluid-project/preferencesServer/blob/main/doc/dataModel.md)" require support by the database, specifically, the  "[Future Data Model](https://github.com/fluid-project/preferencesServer/blob/main/doc/dataModel.md#future-data-model)".

While the initial data model support was tracked on the [`datamodels-postgres`](https://github.com/klown/preferencesServer/tree/datamodels-postgres) branch -- issue #4 -- that work has been folded into the `basic-postgres-support` branch.

Work is tracked on this branch:  https://github.com/klown/preferencesServer/tree/basic-postgres-support

**Comment by klown** [comment]
Current work for this is found at:
https://github.com/klown/preferencesServer/tree/basic-postgres-support

**Comment by cindyli** [comment]
Resolved with the merge of https://github.com/fluid-project/personal-data-server/pull/12
