### ISSUE TITLE
OAuth2 support for authorized database access

### ISSUE THREAD

**Issue by klown** [fluid-project/personal-data-server#3]
Support for authorized access to the preferences is a requirement for the service.  The idea is to use much of the GPII's OAuth2 service, but to:
- disentangle it from the GPII Flowmanager
- have it operate with Postgres instead of Couchdb.

The work is tracked here:
https://github.com/klown/preferencesServer/tree/oauth2

Specifics:
- Documentation:
  - Authorization Server: https://github.com/klown/preferencesServer/blob/oauth2/doc/AuthServer.md
  - Authorization Service: https://github.com/klown/preferencesServer/blob/oauth2/doc/AuthorizationService.md
  - Authorization Grant Finder: https://github.com/klown/preferencesServer/blob/oauth2/doc/AuthGrantFinder.md
- Code: https://github.com/klown/preferencesServer/blob/oauth2/src/oauth2

**Comment by cindyli** [comment]
Resolved with the merge of https://github.com/fluid-project/personal-data-server/pull/12
