### ISSUE TITLE
Define the API for Personal Data Server

### ISSUE THREAD

**Issue by klown** [fluid-project/personal-data-server#5]
The main goal of this project is to provide RESTful access to users' preferences.  Documentation of the preferences server endpoints is needed.

The following is based on GPII's [Preferences Server API](https://github.com/GPII/universal/blob/master/documentation/PreferencesServer.md). This is a first pass; comments are welcome.

- healthy: `GET /health`
  - indicates whether the preferences server is running
- ready: `GET /ready`
  - is the server up and connected to other parts of the system (e.g., database) and those other parts are ready.
- ready: `GET /sso/google`
  - login Personal Data Server via a Google account.
- retrieve preferences: `GET /get_prefs`
  - get current preferences for the given user
  - the user's login token is sent in the request via "Authorization" header
- create/update preferences: `POST /save_prefs`
  - add and update preferences for the given user
  - the user's login token is sent in the request via "Authorization" header

**Comment by klown** [comment]
Based on WeCount technical meeting (25-Feb-2021), there will be an endpoint that provides a list of SSO providers supported by the server:

- GET /preferences/sso/providers
- return a `json` object listing and possibly their SSO endpoint:
```
{
  "Google": "https://accounts.google.com/o/oauth2/auth/",
  "Github": "https://api.github.com/login/oauth/authorize/",
   ...
}
```
Note that Google's oauth2 endpoint requires a `client_id`, a `redirect_uri`, a `scope`, a `response_type`, a `state`, and an `access_type`.  The full URL is:

https://accounts.google.com/o/oauth2/auth
- ?client_id = random characters previously generated  by Google and known to the client that identifies the oauth2 client,
- &redirect_uri = uri that Google calls after it has confirmed that the user is legitimate.  This has previously been registered with Google and is used by Google to call back to the client identified by the `client_id`.  If the value passed here does not match what Google has stored, the oauth2 sequence stops,
- &scope = email https://www.googleapis.com/auth/classroom.rosters.readonly openid profile,
- &response_type = code (yes, literally "code"),
- &state = random characters generated by the client and echoed by Google and the client for the remainder of the current oauth2 exchange,
- access_type = offline

Regarding the `client_id` and `redirect_uri`:  the `client_id` is generated by Google during a manual registration process using the Google developer dashboard.  The `redirect_uri` is set during this registration to whatever the client wants it to be.  (A `client_secret` is also generated by Google during registration, and it is up to the client to store all three of these, typically in the client's own database, also using a manual process).

Regarding `scope`:  this lists what the client wants access to with respect to the user's Google account.  The example above lists the user's gmail address, read-only access to their classroom rosters , their Google openid, and their Google profile.  Google will present a dialog asking the user to confirm access, but only the first time.  After the user confirms, Google will store the confirmed scopes within the user's profile so the confirmation step can be skipped in future.

Regarding the `access_type`, Google supports both "offline" and "online".  Offline means that Google will generate both an access token and a refresh token.  Access tokens expire usually after an hour.  If the client requests and receives a refresh token, it can, when the current access token expires, request a new access token.  In this way the user does not appear to ever lose their connection with the client.  If no refresh token is granted, or even not requested (`access_type=online`), then access  is denied when the access token expires, and the user will have to go through the SSO process again.

**Comment by jobara** [comment]
@klown, thanks for writing this up. Thinking back to our meeting with @amb26 and @cindyli, I wonder if what you've discovered about the Google oauth flow is going to be a problem for what we had planned. I believe, and please correct me if/where I'm mistaken, we had talked about the integrator (the site/application/service consuming the preferences) would need to implement the UI for logging into the SSO. The integrator would make a call to the preferences server for example at the `/preferences/sso/providers` endpoint and use that to generate the UI and trigger the authentication to the correct SSO provider. However, in what you've outlined above it seems that the `client_id` shouldn't be shared with the integrator, the `redirect_uri` wouldn't be known by the prefs server, and the `state` would also need to be communicated between the prefs servers and the SSO. I'm thinking we may still need the prefs server to act as a proxy in between the integrator and SSO to manage all of these bits. 

We had discussed the Preferences Server really being an instance of a more general Personal Storage Server. If that still holds, I think we should either create a new repository for that, or rename this repository to reflect that.
