### ISSUE TITLE
Document the OAuth2 sequence for static sites and Edge Proxy Server secure access to the preferences server

### ISSUE THREAD

**Issue by klown** [fluid-project/personal-data-server#7]
## The Problem
The user is interacting with a web site that has a preferences editor embedded into its pages, for example, UIO+.  The user wants to retrieve and/or save their UIO+ preferences to the preferences server.  Access to the preferences server is secure.

For a more complete description of the issues, see "[GPII Preferences Edge Proxy Refinement I"](https://wiki.fluidproject.org/display/fluid/GPII+Preferences+Edge+Proxy+Refinement+I#GPIIPreferencesEdgeProxyRefinementI-Workflow).

What is needed is documentation of the OAuth2 sequence of requests, responses, their payloads, and what is stored in various databases to realize the interaction outlined there.

**Comment by cindyli** [comment]
Resolved with the merge of https://github.com/fluid-project/personal-data-server/pull/8.
