### ISSUE TITLE
Implement single sign on workflow using Google

### ISSUE THREAD

**Issue by klown** [fluid-project/personal-data-server#9]
## Is your feature request related to a problem?
The personal data server will support a static workflow where a user connected to a server will make requests through it to store, retrieve, or modify their preferences on the personal data server.  The personal data server needs to verify a user's authorization to do so, and the first implementation will use Google's authorization service for this purpose.

## Describe the solution you'd like
Implement an OAuth2 workflow for single sign on (SSO) with Google as the provider.

**Comment by cindyli** [comment]
Resolved with the merge of https://github.com/fluid-project/personal-data-server/pull/12
